---
title: Introduction
format: 
    html:
        code-fold: true
toc: True
# bibliography: reference.bib
---

Explore the evolving climate trends in Southeastern Utah through a comprehensive data-driven analysis highlighting significant changes in temperatures, soil moisture, evaporation and precipitation over the years

# Overview

For the preservation of Southeastern Utah Group National Parks, it is essential to understand the trends that lie in the evolving climate conditions and how they might impact the region's delicate ecosystems. This is an in-depth exploration and analysis of the interconnected effects of heat, soil conditions, and precipitation on the national parks. 

```{r}
library(reticulate)

use_condaenv("base", required = TRUE)
```

# Temperature Tales
```{python}
#| echo: true
#| eval: true 
#| file: code/heat-geo.py
#| fig-cap: This geospatial visualization highlights the maximum temperatures reached within a year across the Southeastern National Parks in Utah. The timeline spans from 1980 to 2024. The animation over the years shows the geographical spread and varying intensity of the highest temperatures in the region.
```

# Summer Heat: On the Rise?

```{python}
#| echo: true
#| eval: true 
#| file: code/heat-trend.py
#| fig-cap: The chart above illustrates the trend in maximum temperatures from 1980 up until the current year. The visualization suggests an overall increase, indicating a trend of rising temperatures in the region.
```

# Next up: 
This raises curiosity to further study the trends in the Summer temperatures of the past and if they are likely to increase in the future  ➡️
